# Generated by Django 5.0.7 on 2024-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=20)),
                ("image", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
