# Generated by Django 5.0.7 on 2024-07-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="image",
            new_name="src",
        ),
    ]
